In [284]:
!pip install numpy pandas

Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.2.4)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/lyebamalik/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/lyebamalik/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [285]:
import numpy as np
import pandas as pd

In [286]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [287]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [288]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [289]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [290]:
movies = movies.merge(credits,on='title')

In [291]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [292]:
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [293]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [294]:
movies.head(5000)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [295]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [296]:
movies.dropna(inplace=True)

In [297]:
movies.duplicated().sum()

np.int64(0)

In [298]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [299]:
import ast
def convert(object):
    L = []
    for i in ast.literal_eval(object):
        L.append(i['name'])
    return L

In [300]:
movies['genres'] = movies['genres'].apply(convert)

In [301]:
movies.head(5000)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [302]:
movies['keywords'] = movies['keywords'].apply(convert)

In [303]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [304]:
import ast
def convert3(object):
    L = []
    counter = 0
    for i in ast.literal_eval(object):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [305]:
movies['cast'] = movies['cast'].apply(convert3)

In [306]:
movies.head(5000)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united statesâ€“mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[Edward Burns, Kerry BishÃ©, Marsha Dietlein]","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton]","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [307]:
import ast
def fetch_director(object):
    L = []
    counter = 0
    for i in ast.literal_eval(object):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [308]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [309]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [310]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [311]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [312]:
movies['genres'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ", "") for i in x])

In [313]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [314]:
movies['tags'] = movies['overview'] +movies['genres'] +movies['keywords']+movies['cast'] + movies['crew']

In [315]:
movies.head(5000)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishÃ©, MarshaDietlein]",[EdwardBurns],"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TV Movie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],"[Ever, since, the, second, grade, when, he, fi..."

In [316]:
new_df = movies[['movie_id', 'title', 'tags']]

In [317]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

/var/folders/c7/15w_xpr16018w9hrqp4fbdsh0000gn/T/ipykernel_13318/3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [318]:
new_df.head(5000)

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [319]:
new_df['tags'][0]
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

/var/folders/c7/15w_xpr16018w9hrqp4fbdsh0000gn/T/ipykernel_13318/2038155300.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [320]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [321]:
import nltk

In [322]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [323]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [324]:
new_df['tags'] = new_df['tags'].apply(stem)

/var/folders/c7/15w_xpr16018w9hrqp4fbdsh0000gn/T/ipykernel_13318/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [325]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi scienc fiction cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [326]:
new_df['tags'][1]

"captain barbossa, long believ to be dead, ha come back to life and is head to the edg of the earth with will turner and elizabeth swann. but noth is quit as it seems. adventur fantasi action ocean drugabus exoticisland eastindiatradingcompani loveofone'slif traitor shipwreck strongwoman ship allianc calypso afterlif fighter pirat swashbuckl aftercreditssting johnnydepp orlandobloom keiraknightley goreverbinski"

In [327]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [328]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [329]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [330]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [331]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy science fiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi scienc fiction cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [332]:
from sklearn.metrics.pairwise import cosine_similarity

In [333]:
similarity = cosine_similarity(vectors)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [334]:
sorted(list(enumerate(similarity[0])), reverse=True, key = lambda x:x[1])[1:6]

[(1214, np.float64(0.30194054243855895)),
 (2405, np.float64(0.28644594961577313)),
 (507, np.float64(0.2710098294963041)),
 (539, np.float64(0.2706659809803833)),
 (1202, np.float64(0.2625754538144587))]

In [335]:
sorted(similarity[0], reverse = True)

[np.float64(1.0000000000000004),
 np.float64(0.30194054243855895),
 np.float64(0.28644594961577313),
 np.float64(0.2710098294963041),
 np.float64(0.2706659809803833),
 np.float64(0.2625754538144587),
 np.float64(0.2614881801842454),
 np.float64(0.26148818018424536),
 np.float64(0.25715142542972574),
 np.float64(0.2562050460881394),
 np.float64(0.249100947511811),
 np.float64(0.24419314525275218),
 np.float64(0.24209101306752093),
 np.float64(0.24198875709123052),
 np.float64(0.24019223070763068),
 np.float64(0.2338821384818744),
 np.float64(0.23076923076923073),
 np.float64(0.22880215766121476),
 np.float64(0.22205779584216376),
 np.float64(0.2201762114819948),
 np.float64(0.21995293510729183),
 np.float64(0.21969401455243584),
 np.float64(0.2196940145524358),
 np.float64(0.2172620473133704),
 np.float64(0.21618989813247),
 np.float64(0.21571674297647797),
 np.float64(0.21571674297647797),
 np.float64(0.21483446221182986),
 np.float64(0.21204880838762138),
 np.float64(0.21182963643408081),
 np.float64(0.20965696734438366),
 np.float64(0.20965696734438366),
 np.float64(0.20814536170751843),
 np.float64(0.20814536170751838),
 np.float64(0.20814536170751838),
 np.float64(0.2080125735844609),
 np.float64(0.20758412292650927),
 np.float64(0.20672455764868075),
 np.float64(0.20483662259967564),
 np.float64(0.2046468711716401),
 np.float64(0.20336295869552104),
 np.float64(0.20180183819889372),
 np.float64(0.20131905799006777),
 np.float64(0.20033416898825337),
 np.float64(0.20033416898825337),
 np.float64(0.20016019225635892),
 np.float64(0.2000625293121421),
 np.float64(0.19814848097530421),
 np.float64(0.19795764159656265),
 np.float64(0.1976664844429603),
 np.float64(0.19535451620220176),
 np.float64(0.19535451620220176),
 np.float64(0.19535451620220173),
 np.float64(0.19223226273338134),
 np.float64(0.19215378456610455),
 np.float64(0.1909639664105154),
 np.float64(0.1909639664105154),
 np.float64(0.1909639664105154),
 np.float64(0.18946618668626833),
 np.float64(0.18887686585995425),
 np.float64(0.18762218965128746),
 np.float64(0.18685673434682065),
 np.float64(0.18490006540840973),
 np.float64(0.1849000654084097),
 np.float64(0.1849000654084097),
 np.float64(0.1849000654084097),
 np.float64(0.18427434427242975),
 np.float64(0.18302666282596894),
 np.float64(0.1815682598006407),
 np.float64(0.1811643254631353),
 np.float64(0.1811643254631353),
 np.float64(0.17902871850985821),
 np.float64(0.17841031003501578),
 np.float64(0.17576348305930709),
 np.float64(0.17505471314812437),
 np.float64(0.17471413945365305),
 np.float64(0.17295817388759027),
 np.float64(0.17255919256291524),
 np.float64(0.17118419700436519),
 np.float64(0.17103344030668952),
 np.float64(0.17093520167692652),
 np.float64(0.17093520167692652),
 np.float64(0.17093520167692652),
 np.float64(0.1706971854997297),
 np.float64(0.1706971854997297),
 np.float64(0.16984155512168939),
 np.float64(0.16984155512168933),
 np.float64(0.16724840200141816),
 np.float64(0.16724840200141816),
 np.float64(0.167093470609201),
 np.float64(0.167093470609201),
 np.float64(0.16694514082354447),
 np.float64(0.16694514082354447),
 np.float64(0.16526725762745997),
 np.float64(0.16526725762745997),
 np.float64(0.1647705109143269),
 np.float64(0.16477051091432687),
 np.float64(0.16401847362094593),
 np.float64(0.16349964255346808),
 np.float64(0.1634301126151534),
 np.float64(0.1634301126151534),
 np.float64(0.16239958858823),
 np.float64(0.16239958858823),
 np.float64(0.16178755723235852),
 np.float64(0.1617875572323585),
 np.float64(0.1613940087116806),
 np.float64(0.1613940087116806),
 np.float64(0.1611258466588724),
 np.float64(0.16012815380508713),
 np.float64(0.16012815380508713),
 np.float64(0.16012815380508713),
 np.float64(0.16012815380508713),
 np.float64(0.16012815380508713),
 np.float64(0.1601281538050871),
 np.float64(0.15794943794779692),
 np.float64(0.15585730003983933),
 np.float64(0.15585730003983933),
 np.float64(0.15534712747612348),
 np.float64(0.15534712747612348),
 np.float64(0.15408338784034142),
 np.float64(0.15384615384615385),
 np.float64(0.15253477177414312),
 np.float64(0.15253477177414312),
 np.float64(0.15253477177414312),
 np.float64(0.15191090506255),
 np.float64(0.1513068831672006),
 np.float64(0.1513068831672006),
 np.float64(0.1513068831672006),
 np.float64(0.15097027121927944),
 np.float64(0.15097027121927944),
 np.float64(0.15004689698410661),
 np.float64(0.15004689698410661),
 np.float64(0.15004689698410661),
 np.float64(0.14978617237881955),
 np.float64(0.14867525836251314),
 np.float64(0.14824986333222023),
 np.float64(0.14718099673591298),
 np.float64(0.14651588715165131),
 np.float64(0.14651588715165131),
 np.float64(0.14651588715165131),
 np.float64(0.14651588715165131),
 np.float64(0.14617633655117152),
 np.float64(0.14617633655117152),
 np.float64(0.14617633655117152),
 np.float64(0.14617633655117152),
 np.float64(0.14484136487558028),
 np.float64(0.1437993271357627),
 np.float64(0.1437993271357627),
 np.float64(0.1437993271357627),
 np.float64(0.1437993271357627),
 np.float64(0.14351616441832768),
 np.float64(0.14322297480788657),
 np.float64(0.14322297480788657),
 np.float64(0.14322297480788657),
 np.float64(0.14235407108686474),
 np.float64(0.1416576493949657),
 np.float64(0.14153462926807447),
 np.float64(0.14153462926807447),
 np.float64(0.14153462926807447),
 np.float64(0.14153462926807445),
 np.float64(0.1401425507601155),
 np.float64(0.1401425507601155),
 np.float64(0.1401425507601155),
 np.float64(0.1401425507601155),
 np.float64(0.14011213457945124),
 np.float64(0.13977131156292244),
 np.float64(0.13977131156292244),
 np.float64(0.13937366833451514),
 np.float64(0.13937366833451512),
 np.float64(0.13797289239745258),
 np.float64(0.13725270326150324),
 np.float64(0.13725270326150324),
 np.float64(0.13725270326150324),
 np.float64(0.13693937303317935),
 np.float64(0.13655774839978377),
 np.float64(0.13655774839978377),
 np.float64(0.13655774839978377),
 np.float64(0.13655774839978377),
 np.float64(0.1358732440973515),
 np.float64(0.1358732440973515),
 np.float64(0.13533299049019168),
 np.float64(0.13533299049019168),
 np.float64(0.1345345587992625),
 np.float64(0.1345345587992625),
 np.float64(0.13355611265883557),
 np.float64(0.13355611265883557),
 np.float64(0.13355611265883557),
 np.float64(0.13355611265883557),
 np.float64(0.13355611265883557),
 np.float64(0.13344012817090595),
 np.float64(0.13344012817090595),
 np.float64(0.13344012817090595),
 np.float64(0.13323467750529824),
 np.float64(0.1320989873168695),
 np.float64(0.1319717610643751),
 np.float64(0.1319717610643751),
 np.float64(0.1316245316231641),
 np.float64(0.1316245316231641),
 np.float64(0.1307440900921227),
 np.float64(0.1307440900921227),
 np.float64(0.1307440900921227),
 np.float64(0.1307440900921227),
 np.float64(0.1307440900921227),
 np.float64(0.13074409009212268),
 np.float64(0.13074409009212268),
 np.float64(0.13074409009212268),
 np.float64(0.12955005512625914),
 np.float64(0.1283881477532739),
 np.float64(0.1283881477532739),
 np.float64(0.1283881477532739),
 np.float64(0.1283881477532739),
 np.float64(0.12820512820512822),
 np.float64(0.12820512820512822),
 np.float64(0.12820512820512822),
 np.float64(0.12820512820512822),
 np.float64(0.12810252304406972),
 np.float64(0.12810252304406972),
 np.float64(0.12810252304406972),
 np.float64(0.12810252304406972),
 np.float64(0.12810252304406972),
 np.float64(0.12810252304406972),
 np.float64(0.12810252304406972),
 np.float64(0.12810252304406972),
 np.float64(0.1281025230440697),
 np.float64(0.12725695259515554),
 np.float64(0.12725695259515554),
 np.float64(0.12725695259515554),
 np.float64(0.12725695259515554),
 np.float64(0.12691660175143157),
 np.float64(0.12659242088545833),
 np.float64(0.12659242088545833),
 np.float64(0.12659242088545833),
 np.float64(0.12659242088545833),
 np.float64(0.12659242088545833),
 np.float64(0.1261107739106075),
 np.float64(0.1258085593493995),
 np.float64(0.12561485860426555),
 np.float64(0.12561485860426555),
 np.float64(0.12561485860426555),
 np.float64(0.12561485860426555),
 np.float64(0.12561485860426555),
 np.float64(0.12561485860426555),
 np.float64(0.12503908082008885),
 np.float64(0.12503908082008885),
 np.float64(0.12503908082008885),
 np.float64(0.12503908082008885),
 np.float64(0.12503908082008885),
 np.float64(0.12503908082008883),
 np.float64(0.12403473458920845),
 np.float64(0.12403473458920844),
 np.float64(0.12403473458920844),
 np.float64(0.12326671027227314),
 np.float64(0.12303443814151495),
 np.float64(0.12301385521570944),
 np.float64(0.12229989761755714),
 np.float64(0.1220965726263761),
 np.float64(0.1220965726263761),
 np.float64(0.12201777521731262),
 np.float64(0.12201777521731262),
 np.float64(0.12201777521731262),
 np.float64(0.12104550653376046),
 np.float64(0.12104550653376046),
 np.float64(0.12104550653376046),
 np.float64(0.12104550653376046),
 np.float64(0.12104550653376046),
 np.float64(0.12104550653376046),
 np.float64(0.1207011373963169),
 np.float64(0.1207011373963169),
 np.float64(0.1207011373963169),
 np.float64(0.1207011373963169),
 np.float64(0.1207011373963169),
 np.float64(0.12009611535381534),
 np.float64(0.12009611535381534),
 np.float64(0.12009611535381534),
 np.float64(0.12009611535381534),
 np.float64(0.12009611535381534),
 np.float64(0.12009611535381534),
 np.float64(0.11935247900657213),
 np.float64(0.11935247900657213),
 np.float64(0.11935247900657213),
 np.float64(0.1191687183448436),
 np.float64(0.11894020669001053),
 np.float64(0.11894020669001053),
 np.float64(0.11894020669001053),
 np.float64(0.11894020669001053),
 np.float64(0.11894020669001053),
 np.float64(0.11894020669001053),
 np.float64(0.11894020669001051),
 np.float64(0.11826247919781652),
 np.float64(0.1180480411624714),
 np.float64(0.11694106924093722),
 np.float64(0.11694106924093722),
 np.float64(0.11694106924093722),
 np.float64(0.11678545896676293),
 np.float64(0.11678545896676293),
 np.float64(0.11678545896676293),
 np.float64(0.1165103456070926),
 np.float64(0.1165103456070926),
 np.float64(0.1165103456070926),
 np.float64(0.1165103456070926),
 np.float64(0.1165103456070926),
 np.float64(0.1165103456070926),
 np.float64(0.11561170597113389),
 np.float64(0.11556254088025608),
 np.float64(0.11556254088025608),
 np.float64(0.11503946170861017),
 np.float64(0.11503946170861017),
 np.float64(0.11503946170861017),
 np.float64(0.11483385035264292),
 np.float64(0.11437725271791938),
 np.float64(0.11437725271791938),
 np.float64(0.11322770341445959),
 np.float64(0.11322770341445959),
 np.float64(0.11322770341445958),
 np.float64(0.11322770341445958),
 np.float64(0.11322770341445958),
 np.float64(0.11322770341445958),
 np.float64(0.11322770341445958),
 np.float64(0.11244949691847501),
 np.float64(0.11211213233271873),
 np.float64(0.11168711865749101),
 np.float64(0.11149893466761211),
 np.float64(0.11149893466761211),
 np.float64(0.11149893466761211),
 np.float64(0.11149893466761211),
 np.float64(0.11102889792108188),
 np.float64(0.11102889792108188),
 np.float64(0.11102889792108188),
 np.float64(0.11102889792108188),
 np.float64(0.11098534863604863),
 np.float64(0.11094003924504581),
 np.float64(0.11020775375559676),
 np.float64(0.11020775375559674),
 np.float64(0.11020775375559674),
 np.float64(0.11020775375559674),
 np.float64(0.11020775375559674),
 np.float64(0.11020775375559674),
 np.float64(0.10997646755364592),
 np.float64(0.10997646755364592),
 np.float64(0.10984700727621793),
 np.float64(0.10984700727621793),
 np.float64(0.10984700727621793),
 np.float64(0.10948978029027179),
 np.float64(0.10878565864408421),
 np.float64(0.10826639239215335),
 np.float64(0.10826639239215334),
 np.float64(0.10826639239215334),
 np.float64(0.10826639239215334),
 np.float64(0.10826639239215334),
 np.float64(0.108094949066235),
 np.float64(0.108094949066235),
 np.float64(0.10795837927188262),
 np.float64(0.1079583792718826),
 np.float64(0.1079583792718826),
 np.float64(0.1079583792718826),
 np.float64(0.10741723110591493),
 np.float64(0.10741723110591493),
 np.float64(0.10741723110591493),
 np.float64(0.10741723110591493),
 np.float64(0.10741723110591493),
 np.float64(0.10741723110591493),
 np.float64(0.10736246830291345),
 np.float64(0.10699012312772824),
 np.float64(0.10699012312772824),
 np.float64(0.10699012312772824),
 np.float64(0.10675210253672475),
 np.float64(0.10675210253672475),
 np.float64(0.10675210253672475),
 np.float64(0.10675210253672475),
 np.float64(0.10604746049596296),
 np.float64(0.10604746049596296),
 np.float64(0.10604746049596296),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.10529962529853128),
 np.float64(0.105129283382795),
 np.float64(0.105129283382795),
 np.float64(0.105129283382795),
 np.float64(0.10482848367219183),
 np.float64(0.10482848367219183),
 np.float64(0.10482848367219183),
 np.float64(0.10482848367219183),
 np.float64(0.10482848367219183),
 np.float64(0.10482848367219183),
 np.float64(0.10423454980627084),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10336227882434038),
 np.float64(0.10300524052492094),
 np.float64(0.10256410256410257),
 np.float64(0.10256410256410257),
 np.float64(0.10256410256410257),
 np.float64(0.10256410256410257),
 np.float64(0.10256410256410257),
 np.float64(0.10256410256410257),
 np.float64(0.10256410256410256),
 np.float64(0.1025115460130912),
 np.float64(0.10241831129983782),
 np.float64(0.10241831129983782),
 np.float64(0.10241831129983782),
 np.float64(0.10241831129983782),
 np.float64(0.10241831129983782),
 np.float64(0.10241831129983782),
 np.float64(0.10168147934776052),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10087125544480038),
 np.float64(0.10016708449412667),
 np.float64(0.10016708449412667),
 np.float64(0.10016708449412667),
 np.float64(0.10008009612817946),
 np.float64(0.10008009612817945),
 np.float64(0.10003126465607108),
 np.float64(0.10003126465607108),
 np.float64(0.10003126465607108),
 np.float64(0.10003126465607108),
 np.float64(0.10003126465607108),
 np.float64(0.10003126465607107),
 np.float64(0.10003126465607107),
 np.float64(0.10003126465607107),
 np.float64(0.09930726528736966),
 np.float64(0.09930726528736966),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09855206599818042),
 np.float64(0.09805806756909204),
 np.float64(0.09805806756909202),
 np.float64(0.09805806756909202),
 np.float64(0.09805806756909202),
 np.float64(0.09805806756909202),
 np.float64(0.09781383788084239),
 np.float64(0.09781383788084239),
 np.float64(0.09781383788084239),
 np.float64(0.09767725810110088),
 np.float64(0.09767725810110088),
 np.float64(0.09767725810110088),
 np.float64(0.09767725810110087),
 np.float64(0.09767725810110087),
 np.float64(0.09767725810110087),
 np.float64(0.09709195467257717),
 np.float64(0.09709195467257717),
 np.float64(0.09656090991705352),
 np.float64(0.09656090991705352),
 np.float64(0.09656090991705352),
 np.float64(0.09656090991705352),
 np.float64(0.09656090991705352),
 np.float64(0.09656090991705352),
 np.float64(0.09656090991705352),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.0954819832052577),
 np.float64(0.0954819832052577),
 np.float64(0.0954819832052577),
 np.float64(0.0954819832052577),
 np.float64(0.0954819832052577),
 np.float64(0.0954819832052577),
 np.float64(0.09501857794816083),
 np.float64(0.09443843292997713),
 np.float64(0.09443843292997713),
 np.float64(0.09421114395319916),
 np.float64(0.09421114395319916),
 np.float64(0.09421114395319916),
 np.float64(0.09421114395319916),
 np.float64(0.09421114395319916),
 np.float64(0.09421114395319916),
 np.float64(0.09421114395319916),
 np.float64(0.09342836717341034),
 np.float64(0.09342836717341034),
 np.float64(0.09342836717341034),
 np.float64(0.09342836717341034),
 np.float64(0.09342836717341034),
 np.float64(0.09342836717341034),
 np.float64(0.09288103752413637),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.0915018021743355),
 np.float64(0.0915018021743355),
 np.float64(0.0915018021743355),
 np.float64(0.0915018021743355),
 np.float64(0.0915018021743355),
 np.float64(0.0915018021743355),
 np.float64(0.0915018021743355),
 np.float64(0.09124148357522648),
 np.float64(0.09078412990032035),
 np.float64(0.09078412990032035),
 np.float64(0.09078412990032035),
 np.float64(0.09078412990032035),
 np.float64(0.09065471553673685),
 np.float64(0.09058216273156766),
 np.float64(0.09058216273156766),
 np.float64(0.09058216273156766),
 np.float64(0.0900791242218625),
 np.float64(0.08968970586617499),
 np.float64(0.08968970586617499),
 np.float64(0.08968970586617499),
 np.float64(0.08968970586617499),
 np.float64(0.08968970586617499),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08896008544727062),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.08861469461982083),
 np.float64(0.08798117404291673),
 np.float64(0.08798117404291673),
 np.float64(0.08788174152965353),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08752735657406219),
 np.float64(0.08716272672808179),
 np.float64(0.08716272672808179),
 np.float64(0.08716272672808179),
 np.float64(0.08716272672808179),
 np.float64(0.08716272672808179),
 np.float64(0.08684168428648435),
 np.float64(0.08684168428648435),
 np.float64(0.08636670341750609),
 np.float64(0.08633531446374632),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),

In [349]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key = lambda x: x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [350]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [351]:
import pickle

In [352]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [354]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))